### ISSUE TITLE
Feat: Add handling static with Select webdriver API & add handling custom dropdowns (ul, li based or div based) feature 

### ISSUE THREAD

**Issue by Imspaliwal** [Imspaliwal/pom-framework#10]
**Is your feature request related to a problem? Please describe.**
Add handling static with Select webdriver API
Add handling custom dropdowns (ul, li based or div based) feature 

**Describe the solution you'd like**
driver able to select the dropdown using these utilities

**Comment by spaliwaldev** [comment]
In case of dynamic dropdown. sometimes dropdown element got disappeared once we do element inspect. user Selector Hub with debug option to freeze the screen and then inspect the elements. 

https://www.youtube.com/watch?v=-uokzf50TbI&ab_channel=NaveenAutomationLabs

**Comment by Imspaliwal** [comment]
Add a feature to handle AutoSuggestive dropdowns using Selenium i.e. Amazon, Flipkart, and Google search

**Comment by Imspaliwal** [comment]
dd a feature to handle AutoSuggestive dropdowns using Selenium i.e. Amazon, Flipkart, and Google search
